### Recursive Solution (Determinant of an n x n Matrix)

In [3]:
import numpy as np

def recursive_determinant(matrix):
    """
    Calculates the determinant of an n x n matrix using recursive cofactor expansion.

    Args:
        matrix: A square numpy array.

    Returns:
        The determinant of the matrix.
    """
    # Ensure the input is a square matrix
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input matrix must be square.")

    n = matrix.shape[0]

    # Base case: for a 1x1 matrix, the determinant is the single element.
    if n == 1:
        return matrix[0, 0]

    # Base case: for a 2x2 matrix, the determinant is ad - bc.
    if n == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

    # Recursive step for n > 2
    determinant = 0
    # We will perform cofactor expansion along the first row (row 0).
    for col_index in range(n):
        # 1. Get the current element from the first row.
        current_val = matrix[0, col_index]
        # 2. Calculate the sign for the cofactor. It alternates (+, -, +, ...).
        # The formula is (-1)^(row + col). Since row is always 0, it's (-1)^col_index.
        sign = (-1) ** col_index
        # 3. Create the submatrix (minor) by removing the current row (0) and column.
        # First, delete row 0.
        submatrix = np.delete(matrix, 0, axis=0)
        # Then, delete the current column from the result.
        minor = np.delete(submatrix, col_index, axis=1)
        # 4. Add the cofactor (sign * value * determinant_of_minor) to the total.
        # The recursive call happens here on the smaller minor matrix.
        determinant += sign * current_val * recursive_determinant(minor)

    return determinant


In [4]:
# --- Example Usage ---

# 3x3 Matrix
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 4x4 Matrix
C = np.array([[3, 2, 0, 1],
              [4, 0, 1, 2],
              [-3, 0, 3, 1],
              [2, 1, -2, 1]])


print("Matrix B:\n", B)
det_B = recursive_determinant(B)
print(f"\nDeterminant of B (calculated recursively): {det_B}")
print(f"Determinant of B (using numpy.linalg.det): {np.linalg.det(B):.2f}")


print("\n" + "="*30 + "\n")


print("Matrix C:\n", C)
det_C = recursive_determinant(C)
print(f"\nDeterminant of C (calculated recursively): {det_C}")
print(f"Determinant of C (using numpy.linalg.det): {np.linalg.det(C):.2f}")

Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of B (calculated recursively): 0
Determinant of B (using numpy.linalg.det): -0.00


Matrix C:
 [[ 3  2  0  1]
 [ 4  0  1  2]
 [-3  0  3  1]
 [ 2  1 -2  1]]

Determinant of C (calculated recursively): -50
Determinant of C (using numpy.linalg.det): -50.00
